In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("C:/Users/Mehak Sood/Downloads/Train.csv",header=None)
data.head()


0                      1  \
0  0   '591764470197723137'   
1  0   '591779538046218240'   
2  0   '591728244925210624'   
3  0   '591774433926193152'   
4  0   '591764472651386882'   

                                                   2  \
0   '#Nepal #news Adding to Bhutanese Refugees Bh...   
1   "The massacre of people's movement says peace...   
2                                        "I'm lonely   
3   '#nepal #news 6 billion collection collection...   
4   '#Nepal #news Indian proposal to crash airpor...   

                                                   3                    4  \
0                                                NaN                  NaN   
1                                                NaN                  NaN   
2   maybe you're going to die without closing the...   I'm going to die."   
3                                                NaN                  NaN   
4                                                NaN                  NaN   

     5    6    7    8  
0  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN

In [3]:
data.isnull().sum()

0        0
1        0
2        0
3    15852
4    17419
5    17927
6    18049
7    18075
8    18085
dtype: int64

In [4]:
data=data.fillna(value="")
data.head()

0                      1  \
0  0   '591764470197723137'   
1  0   '591779538046218240'   
2  0   '591728244925210624'   
3  0   '591774433926193152'   
4  0   '591764472651386882'   

                                                   2  \
0   '#Nepal #news Adding to Bhutanese Refugees Bh...   
1   "The massacre of people's movement says peace...   
2                                        "I'm lonely   
3   '#nepal #news 6 billion collection collection...   
4   '#Nepal #news Indian proposal to crash airpor...   

                                                   3                    4 5 6  \
0                                                                               
1                                                                               
2   maybe you're going to die without closing the...   I'm going to die."       
3                                                                               
4                                                                               

  7 8  
0      
1      
2      
3      
4

In [5]:
data["texts"] = data[2].map(str)+data[3].map(str)+data[4].map(str)+data[5].map(str)+data[6].map(str)+data[7].map(str)+data[8].map(str)


In [6]:
data.head()

0                      1  \
0  0   '591764470197723137'   
1  0   '591779538046218240'   
2  0   '591728244925210624'   
3  0   '591774433926193152'   
4  0   '591764472651386882'   

                                                   2  \
0   '#Nepal #news Adding to Bhutanese Refugees Bh...   
1   "The massacre of people's movement says peace...   
2                                        "I'm lonely   
3   '#nepal #news 6 billion collection collection...   
4   '#Nepal #news Indian proposal to crash airpor...   

                                                   3                    4 5 6  \
0                                                                               
1                                                                               
2   maybe you're going to die without closing the...   I'm going to die."       
3                                                                               
4                                                                               

  7 8                                              texts  
0       '#Nepal #news Adding to Bhutanese Refugees Bh...  
1       "The massacre of people's movement says peace...  
2       "I'm lonely maybe you're going to die without...  
3       '#nepal #news 6 billion collection collection...  
4       '#Nepal #news Indian proposal to crash airpor...

In [7]:
data=data.drop(columns=[2,3,4,5,6,7,8],axis=1)

In [8]:
data.shape

(18086, 3)

In [9]:
data["texts"][0]

" '#Nepal #news Adding to Bhutanese Refugees Bhutanese citizens of Nepalese origin still refrain from leaving their bags.'"

In [10]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stopword = set(stopwords.words('english'))
data['texts'] = data['texts'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopword)]))


[nltk_data] Downloading package stopwords to C:\Users\Mehak
[nltk_data]     Sood\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
from sklearn.feature_extraction import  text

In [12]:
vect=text.TfidfVectorizer()

In [13]:
X=vect.fit_transform(data["texts"])

In [14]:
X.shape

(18086, 17081)

In [15]:
vect.vocabulary_

{'nepal': 10091,
 'news': 10203,
 'adding': 823,
 'bhutanese': 2242,
 'refugees': 12246,
 'citizens': 3127,
 'nepalese': 10127,
 'origin': 10643,
 'still': 14138,
 'refrain': 12240,
 'leaving': 8618,
 'bags': 1782,
 'the': 14864,
 'massacre': 9202,
 'people': 11055,
 'movement': 9702,
 'says': 13079,
 'peace': 11023,
 'constitution': 3480,
 'lost': 8860,
 'country': 3633,
 'lonely': 8831,
 'maybe': 9252,
 'going': 6252,
 'die': 4337,
 'without': 16342,
 'closing': 3187,
 'city': 3128,
 'love': 8872,
 'leave': 8616,
 'billion': 2281,
 'collection': 3250,
 '12': 55,
 'one': 10536,
 'year': 16589,
 'half': 6528,
 '30': 225,
 'thousand': 14945,
 'foreign': 5810,
 'studies': 14233,
 'indian': 7332,
 'proposal': 11712,
 'crash': 3675,
 'airport': 1023,
 'crashes': 3677,
 'four': 5857,
 'days': 3921,
 'god': 6231,
 'also': 1113,
 'ran': 12035,
 'away': 1688,
 'money': 9607,
 'poor': 11358,
 'listened': 8746,
 'asked': 1515,
 'for': 5793,
 'someone': 13875,
 'feels': 5581,
 'like': 8706,
 'til

In [16]:
data.head()

0                      1                                              texts
0  0   '591764470197723137'  '#Nepal #news Adding Bhutanese Refugees Bhutan...
1  0   '591779538046218240'  "The massacre people's movement says peace con...
2  0   '591728244925210624'  "I'm lonely maybe going die without closing ci...
3  0   '591774433926193152'  '#nepal #news 6 billion collection collection ...
4  0   '591764472651386882'  '#Nepal #news Indian proposal crash airport cr...

In [17]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [18]:
y= pd.DataFrame(data[0])

In [19]:
data_new=SelectKBest(chi2,k=2).fit_transform(X,y)

In [20]:
data_new.shape

(18086, 2)

In [21]:
from sklearn.model_selection import StratifiedShuffleSplit

In [22]:
shuffle=StratifiedShuffleSplit(n_splits=9,random_state=6)

In [23]:
y=y.values.reshape(18086)

In [24]:
for train_index, test_index in shuffle.split(data_new, y):
    X_train, X_test = data_new[train_index], data_new[test_index]
    y_train, y_test = y[train_index], y[test_index]

Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB


In [26]:
gass = GaussianNB()
gass.fit(X_train.todense(),y_train)

GaussianNB(priors=None)

In [27]:
pre_gass =  gass.predict(X_test.todense())

In [28]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

In [29]:
accuracy_score(pre_gass,y_test)

0.9469320066334992

In [30]:
print(classification_report(pre_gass,y_test))

             precision    recall  f1-score   support

          0       0.98      0.97      0.98      1733
          1       0.10      0.40      0.16         5
          2       0.39      0.37      0.38        71

avg / total       0.95      0.95      0.95      1809



In [31]:
print(confusion_matrix(pre_gass,y_test))

[[1685   10   38]
 [   1    2    2]
 [  37    8   26]]


In [32]:
f1_gass = f1_score(pre_gass,y_test,average='weighted')
print(f1_gass)

0.94948838242852


In [33]:
from sklearn.naive_bayes import MultinomialNB

In [34]:
multi = MultinomialNB()
multi.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [35]:
pre_multi = multi.predict(X_test)

In [36]:
print(accuracy_score(pre_multi,y_test)*100)

95.24599226091763


In [37]:
print(classification_report(pre_multi,y_test))

             precision    recall  f1-score   support

          0       1.00      0.95      0.98      1809
          1       0.00      0.00      0.00         0
          2       0.00      0.00      0.00         0

avg / total       1.00      0.95      0.98      1809



C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [38]:
print(confusion_matrix(pre_multi,y_test))

[[1723   20   66]
 [   0    0    0]
 [   0    0    0]]


In [39]:
f1_multi = f1_score(pre_multi,y_test,average='weighted')
print(f1_multi)

0.9756511891279728


C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Support Vector Machine

In [40]:
from sklearn.svm import SVC

In [41]:
linear_svc = SVC(kernel = "linear")
linear_svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
pre_lin_SVC =linear_svc.predict(X_test)

In [43]:
print(accuracy_score(pre_lin_SVC,y_test))

0.9519071310116086


In [44]:
print(classification_report(pre_lin_SVC,y_test))

             precision    recall  f1-score   support

          0       0.99      0.96      0.98      1780
          1       0.00      0.00      0.00         0
          2       0.21      0.48      0.29        29

avg / total       0.98      0.95      0.96      1809



C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [45]:
print(confusion_matrix(pre_lin_SVC,y_test))

[[1708   20   52]
 [   0    0    0]
 [  15    0   14]]


In [46]:
f1_lin_SVC = f1_score(pre_lin_SVC,y_test,average='weighted')
print(f1_lin_SVC)

0.9642562446401778


C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [47]:
poly_SVC  = SVC(kernel="poly",degree=8)

In [48]:
poly_SVC.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
pre_pol_SVC=poly_SVC.predict(X_test)

In [50]:
print(accuracy_score(pre_pol_SVC,y_test)*100)

95.24599226091763


In [51]:
print(classification_report(pre_pol_SVC,y_test))

             precision    recall  f1-score   support

          0       1.00      0.95      0.98      1809
          1       0.00      0.00      0.00         0
          2       0.00      0.00      0.00         0

avg / total       1.00      0.95      0.98      1809



C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [52]:
print(confusion_matrix(pre_pol_SVC,y_test))

[[1723   20   66]
 [   0    0    0]
 [   0    0    0]]


In [53]:
f1_pol_SVC = f1_score(pre_pol_SVC,y_test,average='weighted')
print(f1_pol_SVC)

0.9756511891279728


C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [54]:
gass_SVC = SVC(kernel="rbf")
gass_SVC.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [55]:
pre_gas_SVC= gass_SVC.predict(X_test)

In [56]:
print(classification_report(pre_gas_SVC,y_test))

             precision    recall  f1-score   support

          0       0.99      0.96      0.97      1779
          1       0.00      0.00      0.00         0
          2       0.21      0.47      0.29        30

avg / total       0.98      0.95      0.96      1809



C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [57]:
print(accuracy_score(pre_gas_SVC,y_test)*100)

95.13543394140409


In [58]:
f1_gas_SVC = f1_score(pre_gas_SVC,y_test,average='weighted')
print(f1_gas_SVC)

0.9635414052271798


C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [59]:
def check(strg):
    a=[]
    from nltk.tokenize import word_tokenize
    nltk.download("punkt")
    word_tokens = word_tokenize(strg)
    
    for w in word_tokens:
        if w not in stopword:
                a.append(w)
    vec = text.TfidfVectorizer()
    st =  vec.fit_transform(a)
    return st

In [60]:
strn = "i need supplies"

In [61]:
abc = check(strn)

[nltk_data] Downloading package punkt to C:\Users\Mehak
[nltk_data]     Sood\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [62]:
gass.predict(abc.todense())

array([1, 2], dtype=int64)

In [63]:
linear_svc.predict(abc)

array([2, 2], dtype=int64)

Decision Tree Classifier

In [64]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
DTree = DecisionTreeClassifier()
DTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [66]:
pre_DTree = DTree.predict(X_test)

In [67]:
print(classification_report(pre_DTree,y_test))

             precision    recall  f1-score   support

          0       0.99      0.96      0.98      1771
          1       0.15      0.60      0.24         5
          2       0.24      0.48      0.32        33

avg / total       0.97      0.95      0.96      1809



In [68]:
print(confusion_matrix(pre_DTree,y_test))

[[1706   16   49]
 [   1    3    1]
 [  16    1   16]]


In [69]:
print(accuracy_score(pre_DTree,y_test))

0.9535655058043118


In [70]:
f1_DTree = f1_score(pre_DTree,y_test,average="weighted")
print(f1_DTree)

0.9625778968373381


Random Forest Classifier

In [71]:
from sklearn.ensemble import RandomForestClassifier

In [72]:
RandT = RandomForestClassifier(n_estimators=100,n_jobs=2,random_state=7)

In [73]:
RandT.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
            oob_score=False, random_state=7, verbose=0, warm_start=False)

In [74]:
pre_RandT = RandT.predict(X_test)

In [75]:
print(classification_report(pre_RandT,y_test))

             precision    recall  f1-score   support

          0       0.99      0.96      0.98      1770
          1       0.15      0.50      0.23         6
          2       0.24      0.48      0.32        33

avg / total       0.97      0.95      0.96      1809



In [76]:
print(confusion_matrix(pre_RandT,y_test))

[[1705   16   49]
 [   2    3    1]
 [  16    1   16]]


In [77]:
print(accuracy_score(pre_RandT,y_test))

0.953012714206744


In [78]:
f1_RandT = f1_score(pre_RandT,y_test,average="weighted")
print(f1_RandT)

0.961853443632923


In [79]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [80]:
estimater = []
model1 = LogisticRegression()
estimater.append(("Logistic",model1))
model2 = KMeans()
estimater.append(("KMeans",model2))
model3 = SVC(kernel="rbf")
estimater.append(("SVC",model3))
model4 = GaussianNB()
estimater.append(("Gaussian",model4))
model5 =  KNeighborsClassifier()
estimater.append(("KNN",model5))

In [81]:
Voti = VotingClassifier(estimater)

In [82]:
Voti.fit(X_train.todense(),y_train)

VotingClassifier(estimators=[('Logistic', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('KMeans...owski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [83]:
pre_Voti = Voti.predict(X_test.todense())

C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [84]:
print(classification_report(pre_Voti,y_test))

             precision    recall  f1-score   support

          0       0.99      0.96      0.98      1785
          1       0.00      0.00      0.00         0
          2       0.18      0.50      0.27        24

avg / total       0.98      0.95      0.97      1809



C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [85]:
print(confusion_matrix(pre_Voti,y_test))

[[1711   20   54]
 [   0    0    0]
 [  12    0   12]]


In [86]:
print(accuracy_score(pre_Voti,y_test))

0.9524599226091763


In [87]:
f1_Voti = f1_score(pre_Voti,y_test,average="weighted")
print(f1_Voti)

0.966080720179667


C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [88]:
app_algo = ["Gassuian Naive Bayes","Multinomial Naive Bayes","Linear SVC","Polynomial_SVC","Gassuian SVC","Decision Tree","Random Forest","Voting"]
F1_res = [f1_gass,f1_multi,f1_lin_SVC,f1_pol_SVC,f1_gas_SVC,f1_DTree,f1_RandT,f1_Voti]

In [89]:
results = pd.DataFrame({"Algo":app_algo,"F1 score":F1_res},index=[1,2,3,4,5,6,7,8])
results

Algo  F1 score
1     Gassuian Naive Bayes  0.949488
2  Multinomial Naive Bayes  0.975651
3               Linear SVC  0.964256
4           Polynomial_SVC  0.975651
5             Gassuian SVC  0.963541
6            Decision Tree  0.962578
7            Random Forest  0.961853
8                   Voting  0.966081

From the above seen results the algo that's working best for the data in train set seems to be Gaussian Naive bayes as its the only one that is classifying in all the classes